languageCode = "en-us"
title = "@jeqo"
baseurl = "https://jeqo.github.io/"

theme = "jeqo-theme"

MetaDataFormat = "yaml"
PygmentsCodeFences = true
PygmentsStyle = "colorful"

copyright = "&copy; Copyright @jeqo"

[params]
  paginate = 10
  twitter = "jeqo89"
  github = "jeqo"
  keybase = "jeqo"
  linkedin = "jeqo89"
  # disqus = "jeqoblog"
  giscus = true
  ga_api_key = "UA-49047812-3"
  author = "Jorge Esteban Quilcate Otoya"
  authorwebsite = "jeqo.github.com"
  avatar = "/images/jeqo.jpg"
  contact = "mailto:quilcate.jorge@gmail.com"
  bio = ""
  subtitle = "data streaming, observability, automation, and random stuff"
  favicon = "/images/favicon.ico"
  mainSections = ["posts", "talks", "notes"]

[Languages]
[Languages.en]
    weight = 1

[[Languages.en.menu.main]]
    name = "Posts"
    pre = ""
    weight = -100
    url = "/posts"

[[Languages.en.menu.main]]
    name = "Notes"
    pre = ""
    weight = -90
    url = "/notes"

[[Languages.en.menu.main]]
    name = "Talks"
    pre = ""
    weight = -80
    url = "/talks"

[[Languages.en.menu.main]]
    name = "Projects"
    pre = ""
    weight = -70
    url = "/projects"

[[Languages.en.menu.main]]
    name = "About"
    pre = ""
    weight = -60
    url = "/about"

[Languages.es]
    url = "/es"
    weight = 2

[[Languages.es.menu.main]]
    name = "Posts"
    pre = ""
    weight = -100
    url = "/es/posts"

[[Languages.es.menu.main]]
    name = "Notas"
    pre = ""
    weight = -90
    url = "/es/notes"

[[Languages.es.menu.main]]
    name = "Proyectos"
    pre = ""
    weight = -70
    url = "/projects"

[[Languages.es.menu.main]]
    name = "Acerca"
    pre = ""
    weight = -60
    url = "/about"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
